#pragma once

/*-----------------------------------------------------------------
* jmp_score.h
* Header file with function prototypes for the 
* C language scoring code generated by JMP.
*
* Required by customer code.
*   - DO NOT define JMP_SCORE_EXPORTS when compiling application
* Required when compiling JMP-generated C language scoring code.
*   - DO define JMP_SCORE_EXPORTS when compiling DLL
*-----------------------------------------------------------------*/

#ifdef JMP_SCORE_EXPORTS
#define JMP_SCORE_API __declspec(dllexport) 
#else
#define JMP_SCORE_API __declspec(dllimport) 
#endif
#include "jmp_parms.h"

#ifdef __cplusplus
extern "C" {
#endif

JMP_SCORE_API void fillMetadataCounts(COUNTS *mc);
JMP_SCORE_API void fillModelMetadata(MODELMD *mm);
JMP_SCORE_API void fillInputMetadata(FIELDMD *fd);
JMP_SCORE_API void fillOutputMetadata(FIELDMD *fd);
JMP_SCORE_API void score(PARM *indata, PARM *outdata);

#ifdef __cplusplus
}
#endif